name: Unit tests

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  unit-tests:
    env:
        POSTGRES_HOST: localhost
        POSTGRES_PORT: 5432
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        POSTGRES_DB: routing
        PYTHONFAULTHANDLER: 1
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        lfs: true

    - name: Checkout LFS objects (map files)
      run: git lfs checkout
      
    - name: Set up Python 3.9.16
      uses: actions/setup-python@v3
      with:
        python-version: 3.9.16
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ./routing
        pip install -r requirements.txt

    - name: Run unit tests
      run: |
        cd routing
        python -m unittest -v
